### ISSUE TITLE
可通过 Post 请求在 Judges 页面 language 字段注入任意文字

### ISSUE THREAD

**Issue by Lemon-412** [oj-lab/platform#110]
效果：https://www.oj-lab.online/judges
![image](https://github.com/user-attachments/assets/5a99fd90-bc5c-4332-9248-adecd08e6c16)

触发方式：
黑盒，调试 submit 按钮找到对应 post 请求
![image](https://github.com/user-attachments/assets/8bb15fc0-2716-472a-8d5a-d89bc73f0320)

疑似后端未校验 submit 按钮的 language 字段的合法性导致的。

/cc @slhmy

**Comment by slhmy** [comment]
Fixed in https://github.com/oj-lab/platform/commit/d6d93e69539fb495ea4a0bea40faacf895c014c3
