### ISSUE TITLE
`cpp` 无法提交报 `500 invalid language`

### ISSUE THREAD

**Issue by Lemon-412** [oj-lab/platform#111]
现象：
在现网任意题目下提交报错 `500`
![7S8ZZZ963A0 $ WY72VOVUT](https://github.com/user-attachments/assets/51ec7521-a4e6-4cfc-895c-d977361484ea)
![O{@NWK{ITNVMSH(_FZDZEQ3](https://github.com/user-attachments/assets/4d867151-a0dd-4079-8d9c-28e4606af2e6)

猜测：
疑似是以下函数造成的
https://github.com/oj-lab/platform/blob/main/models/judge/judge.go#L31

如图，正常请求 language 应当为 `cpp`？
![image](https://github.com/user-attachments/assets/79b183fb-d0fb-4a04-9c28-16d3cf834b5d)

**Comment by slhmy** [comment]
Fixed
